<?php
    require "./vendor/autoload.php";
    require "Models/Supplier.php";
    require "Models/Customer.php";
    require "Models/Category.php";
    require "DatabaseOperation.php";
    require "Models/utils.php";
    require "Models/Item.php";
    require "Models/Purchase.php";
    require "Models/Driver.php";
    require "Models/Expences.php";
    require "Models/Employee.php";
    require "Models/CreditSettlement.php";
    require "Models/Basic.php";
    require "Models/Order.php";
    require "Models/Report.php";
    require "Models/Income.php";
    require "Token.php";
    require "Auth.php";